; CONVERTING NUMBERS TO THEIR TWOS COMPLEMENT
CODE SEGMENT
    ASSUME CS:CODE, DS:CODE
    
    org 1000h
    
    MOV CX,5  ; SINCE WE TOOK 5 ELEMENTS IN THE ARRAY
    MOV DI,0
NEGATIUE_NUMBERS:
    MOV AX,[A+DI]
    NEG AX 
    MOV [B+DI],AX 
    ADD DI,2 
    LOOP NEGATIUE_NUMBERS
    HLT
    
ORG 050h
A DW 1h,0FFFh,0F056h,1056h,4059h

ORG 060h
B DW ?,?,?,?,?
   
        
CODE ENDS 
END