CODE SEGMENT 
 ASSUME CS:CODE, DS:CODE 
 
 MOV AL,1101b
 MOV BL,11b
 
 MOV DL,AL ; FOR ADDING 
 ;MOV DL,AL ; FOR THE LAST DIGIT LOOP 
 MOV CX,8
 MOV AX, 0
 
ADD_AND_SHIFT_LOOP:
 RCR BL,1
 JNC ADD_TIMES_ZERO 
ADD_TIMES_ONE:
 ADD AX,DX
 SHL DL,1
 JMP PRE_LOOP
ADD_TIMES_ZERO:
 ADD AX,0
 SHL DL,1
 JMP PRE_LOOP
PRE_LOOP:

LOOP ADD_AND_SHIFT_LOOP 
 HLT
CODE ENDS 
 END 