; Main.asm file generated by New Project wizard
;
; Created:   Fri May 28 2021
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
	 P_A EQU 00H  
	 P_B EQU 02H 
	 P_C EQU 04H 
	 CONNECT EQU 06H 
DATA ENDS

CODE SEGMENT
      ASSUME CS:CODE
      ASSUME DS:CODE
      ASSUME ES:CODE
      ASSUME SS:CODE

      ORG 0000H ; 
      MOV AX, DATA
      MOV DS, AX 
      MOV AL, 10000000B ; 
      OUT CONNECT, AL
      
MAIN_LOOP:
      ; HUNDREADTH POSITIONAL DATA
      MOV AL, 11000000B 
      OUT P_A, AL 
      ; TENTH POSITIONAL DATA
      MOV AL, 10110000B
      OUT P_B, AL 
      ; UNIT POSITIONAL DATA
      MOV AL, 10000000B
      OUT P_C, AL ; Output data

JMP MAIN_LOOP 
CODE ENDS
END ; 